server:
  port: 8750
eureka:
  instance:
    hostname: peer2
  client:
    #是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: true
    #表示是否从Eureka Sever获取注册信息，默认为true。因为这个Eureka Server需要同步其他的Eureka Server节点的数据，故而设为true
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://peer1:8760/eureka
#两个项目的spring.application.name必须相同，eureka.instance.hostname必须不同
spring:
  application:
    name: eureka-server

