spring:
  application:
    # 指定注册到Eureka Server上的应用名称
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8750/eureka
  instance:
    # 将自己的IP注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server
    prefer-ip-address: true

server:
  port: 8761