server:
  port: 8040
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故而设为false
    register-with-eureka: false
    #表示是否从Eureka Sever获取注册信息，默认为true。因为这个一个单节点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
spring:
  security:
    user:
      name: root
      password: root